### ISSUE TITLE
Installed & Restarted... now what?

### ISSUE THREAD

**Issue by bstanley78** [leroyguillaume/keycloak-bcrypt#2]
I've followed the installation instructions in your readme, but I'm unsure what the next steps are and can't find documentation online to help.

I have `jbcrypt-0.4.jar.deployed` in my `/opt/jboss/keycloak/standalone/deployments` folder.  I think the next step is to enable the hashing algorithm (see attached image) but I'm unsure what to use for the `value` field.  Any help would be appreciated!

![image](https://user-images.githubusercontent.com/1598844/56743524-54ce0f80-673c-11e9-8e22-4cc5b254c462.png)

**Comment by leroyguillaume** [comment]
Normally, you can see bcrypt in available providers list (settings > providers view). If you want to use it by default, you need to replace pbkdf2-sha256 by bcrypt. I hope it helps.

**Comment by bstanley78** [comment]
Hmm, so I should see bcrypt here?

![image](https://user-images.githubusercontent.com/1598844/56746341-a200b000-6741-11e9-9d24-22b1e1ceb2ff.png)

When I try to enter `bcrypt` in the `policy value` textbox, I get the following error:

![image](https://user-images.githubusercontent.com/1598844/56746452-db392000-6741-11e9-892c-c656bcc9b97c.png)

**Comment by leroyguillaume** [comment]
No, in server > setting > providers view.

The policy value should work. What's your version of Keycloak? You don't have any error at startup?

**Comment by bstanley78** [comment]
I'm using the latest docker image from jboss/keycloak, which is 6.0.1

![image](https://user-images.githubusercontent.com/1598844/56748379-5bad5000-6745-11e9-837a-1ff2528eda6b.png)

Bcrypt is not listed in the server > setting > providers view:

![image](https://user-images.githubusercontent.com/1598844/56748508-99aa7400-6745-11e9-82ac-9ec06d5e8a38.png)

There aren't any errors on startup - just a few random warnings but nothing related to bcrypt.

**Comment by leroyguillaume** [comment]
Oh... I don't know if this module works with the latest Keycloak version. I just merged dependency upgrade to Keycloak 4 from a fork. Can you try with this version?

**Comment by bstanley78** [comment]
You are the man.  Confirmed, this now works on 6.0.1

![image](https://user-images.githubusercontent.com/1598844/56752206-62d85c00-674d-11e9-9f82-4b4e7e7e5ad3.png)

![image](https://user-images.githubusercontent.com/1598844/56752265-7c79a380-674d-11e9-819a-462f8dd57f15.png)

**Comment by bstanley78** [comment]
Thanks again!

**Comment by leroyguillaume** [comment]
Glad to have been able to help! And thank you for your interest about this project!

**Comment by VenkateshGuntuk** [comment]
Hi,

I'm getting same issue I followed all the steps giving in readme...also deployed the jar in  keycloak/standalone/deployments and restarted keycloak server but bcyrpt is not enlisted in Password-Hashing section...is there anything m missing here???

**Comment by VenkateshGuntuk** [comment]
I am using  keycloak's latest version

**Comment by leroyguillaume** [comment]
Hi!

What's version of Keycloak do you use?

**Comment by VenkateshGuntuk** [comment]
6.0.1

**Comment by leroyguillaume** [comment]
And what's version of keycloak-bcrypt do you use? Do you see anything in Keycloak logs?

**Comment by VenkateshGuntuk** [comment]
I'm getting issue while starting keycloak server

**Comment by VenkateshGuntuk** [comment]
12:31:20,659 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."keycloak-bcrypt-1.1.0.jar".STRUCTURE: org.jboss.msc.service.StartException in service jboss.deployment.unit."keycloak-bcrypt-1.1.0.jar".STRUCTURE: WFLYSRV0153: Failed to process phase STRUCTURE of deployment "keycloak-bcrypt-1.1.0.jar"
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:183)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
        at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYSRV0160: Failed to mount deployment content
        at org.jboss.as.server.deployment.module.DeploymentRootMountProcessor.deploy(DeploymentRootMountProcessor.java:95)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:176)
        ... 8 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.jboss.vfs.spi.JavaZipFileSystem.<init>(JavaZipFileSystem.java:90)
        at org.jboss.vfs.spi.JavaZipFileSystem.<init>(JavaZipFileSystem.java:77)
        at org.jboss.vfs.VFS.mountZip(VFS.java:386)
        at org.jboss.vfs.VFS.mountZip(VFS.java:410)
        at org.jboss.as.server.deployment.DeploymentMountProvider$Factory$ServerDeploymentRepositoryImpl.mountDeploymentContent(DeploymentMountProvider.java:108)
        at org.jboss.as.server.deployment.module.DeploymentRootMountProcessor.deploy(DeploymentRootMountProcessor.java:91)
        ... 9 more

**Comment by VenkateshGuntuk** [comment]
not able to unzip "keycloak-bcrypt-1.1.0.jar" using winrar which I have just downloaded using below command...

curl https://github.com/leroyguillaume/keycloak-bcrypt/releases/download/1.1.0/keycloak-bcrypt-1.1.0.jar > keycloak-bcrypt-1.1.0.jar

**Comment by leroyguillaume** [comment]
Oh, I forgot `-L` option in the `curl` command, I'm sorry...

**Comment by leroyguillaume** [comment]
I updated the README!

Thank you for your feedback!

**Comment by VenkateshGuntuk** [comment]
You just saved my day...Thank You

**Comment by leroyguillaume** [comment]
You're welcome!

**Comment by Jonaslc** [comment]
Boa tarde,
Baixei o jar na pasta deployments mas ao subir o keycloak, ele gera um arquivo contendo esse erro e não sobre o plugin

"{\"WFLYCTL0080: Failed services\" => {\"jboss.module.service.\\\"deployment.keycloak-bcrypt-1.1.0.jar\\\".main\" => \"WFLYSRV0179: Failed to load module: deployment.keycloak-bcrypt-1.1.0.jar
    Caused by: org.jboss.modules.ModuleLoadException: Error loading module from /opt/keycloak/modules/org/mindrot/jbcrypt/main/module.xml
    Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add resource root 'jbcrypt-0.4.jar' at path 'jbcrypt-0.4.jar' (position: END_TAG seen ...<resources>\\\\n        <resource-root path=\\\"jbcrypt-0.4.jar\\\"/>... @6:48) caused by: java.util.zip.ZipException: zip END header not found
    Caused by: java.util.zip.ZipException: zip END header not found\"}}"

O que poderia ser?

**Comment by Jonaslc** [comment]
Boa tarde,
Este jar está vindo corrompido: curl http://central.maven.org/maven2/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar > jbcrypt-0.4.jar

Att.
